### ISSUE TITLE
FR: rss feed

### ISSUE THREAD

**Issue by greghab** [felixroos/felixroos.github.io#1]
So individuals can subscribe to the blog in their feed reader, and not need to manually check it in their browser for updates.
If easy to implement, would be cool.

-------
- And just a note: this strudel one you made is pretty nuts, it's really really good:  https://strudel.tidalcycles.org/?qO1vsHQkfEaj

**Comment by felixroos** [comment]
hey! I there are 2 feed files:

- https://loophole-letters.vercel.app/rss.xml 
- https://loophole-letters.vercel.app/atom.xml

I thought this was working but I haven't checked for longer..

I am also already building a new version of the blog [here](https://loophole-letters.netlify.app/) with https://loophole-letters.netlify.app/rss.xml

**Comment by greghab** [comment]
Sounds good. I'll add that [https://loophole-letters.netlify.app/rss.xml](https://loophole-letters.netlify.app/rss.xml) to my rss reader.
- **I guess adding a link to that rss url somewhere on the site would be cool though, so it's posted, and discoverable.**

But I'll close this, as this is asked and answered. Appreciate it.

-----
I believe I originally tried to guess the rss path as [https://loophole-letters.vercel.app/rss](https://loophole-letters.vercel.app/rss), which is a 404.  So I guess I need to add that `.xml` to it, as stated. It seems rss paths vary, depending on the site.
- Some non `rss.xml` examples:
   - https://blog.codinghorror.com/rss/
   - https://steve-yegge.medium.com/feed
   - https://hnrss.org/best
